version: "2"
run:
  concurrency: 4
  go: "1.19"
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
  sort-order:
    - file
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - depguard
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - gocyclo
    - godot
    - gomoddirectives
    - gomodguard
    - gosec
    - gosmopolitan
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - unparam
    - zerologlint
  disable:
    - contextcheck
    - err113
    - godox
    - testifylint
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        errors:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: github.com/pkg/errors
              desc: pkg/errors is deprecated, use errors package from stdlib
        main:
          list-mode: lax
          files:
            - '!$test'
            - '!**/plugins/**'
          deny:
            - pkg: github.com/aws/aws-sdk-go
              desc: aws-sdk-go dependants must be in plugins/aws-v1
    funlen:
      lines: 70
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - godot
          - gosec
          - perfsprint
        path: _test\.go
      - linters:
          - staticcheck
        path: plugins/aws-v1/
        text: SA1019.*aws-sdk-go.*deprecated
      - linters:
          - staticcheck
        path: pkg/(kms|persistence)/
        text: SA1019.*is deprecated.*AWS SDK v1 reached end-of-life
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/godaddy/asherah/go/appencryption)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
