coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 5%
      csharp-AppEncryption:
        flags:
          - csharp_AppEncryption
        target: 90%
      csharp-Logging:
        flags:
          - csharp_Logging
        target: 90%
      csharp-SecureMemory:
        flags:
          - csharp_SecureMemory
        target: 90%
      go-securememory:
        flags:
          - go_securememory
        target: 90%
      go-appencryption:
        flags:
          - go_appencryption
        target: 90%
      java-app-encryption:
        flags:
          - java_app_encryption
        target: 90%
      java-secure-memory:
        flags:
          - java_secure_memory
        target: 90%
      server-go:
        flags:
          - server_go
        target: 90%
      server-java:
        flags:
          - server_java
        target: 90%
# Note flags have to be "\w" charset (hence underscore instead of hyphen)
flags:
  csharp_AppEncryption:
    paths:
      - csharp/AppEncryption
  csharp_Logging:
    paths:
      - csharp/Logging
  csharp_SecureMemory:
    paths:
      - csharp/SecureMemory
  go_securememory:
    paths:
      - go/securememory
  go_appencryption:
    paths:
      - go/appencryption
  java_app_encryption:
    paths:
      - java/app-encryption
  java_secure_memory:
    paths:
      - java/secure-memory
  server-go:
    paths:
      - server/go
  server-java:
    paths:
      - server/java
ignore:
  # Ignore non-linux native paths,auto-generated files and server startup files
  - "**/com/godaddy/asherah/securememory/protectedmemoryimpl/macos" # java macos path
  - "**/target/generated-sources/protobuf/java/com/godaddy/asherah/grpc"
  - "**/target/generated-sources/protobuf/grpc-java/com/godaddy/asherah/grpc"
  - "**/com/godaddy/asherah/grpc/ServerApp.java"
