coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 5%
      csharp-AppEncryption:
        flags:
          - csharp_AppEncryption
        target: 90%
      csharp-Logging:
        flags:
          - csharp_Logging
        target: 90%
      csharp-SecureMemory:
        flags:
          - csharp_SecureMemory
        target: 90%
      go-securememory:
        flags:
          - go_securememory
        target: 90%
      go-appencryption:
        flags:
          - go_appencryption
        target: 90%
      java-app-encryption:
        flags:
          - java_app_encryption
        target: 90%
      java-secure-memory:
        flags:
          - java_secure_memory
        target: 90%
      server-go:
        flags:
          - server_go
        target: 90%
      server-java:
        flags:
          - server_java
        target: 90%
# Note flags have to be "\w" charset (hence underscore instead of hyphen)
flags:
  csharp_AppEncryption:
    paths:
      - csharp/AppEncryption
  csharp_Logging:
    paths:
      - csharp/Logging
  csharp_SecureMemory:
    paths:
      - csharp/SecureMemory
  go_securememory:
    paths:
      - go/securememory
  go_appencryption:
    paths:
      - go/appencryption
  java_app_encryption:
    paths:
      - java/app-encryption
  java_secure_memory:
    paths:
      - java/secure-memory
  server-go:
    paths:
      - server/go
  server-java:
    paths:
      - server/java
ignore:
  # Non-linux native paths. Ideally, be nice to setup separate OS-specific builds.
  - "**/com/godaddy/asherah/securememory/protectedmemoryimpl/macos" # java macOS path
  - "**/SecureMemory/ProtectedMemoryImpl/MacOS" # C# macOS path
  - "**/SecureMemory/ProtectedMemoryImpl/Windows" # C# Windows path
  # gRPC auto-generated file
  - "**/target/generated-sources/protobuf" # Java auto-generated files
  - "**api/appencryption.pb.go" # Go auto-generated files
  # Server startup files
  - "**/com/godaddy/asherah/grpc/ServerApp.java" # Java server startup
