version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
  sort-order:
    - file
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - gocyclo
    - godot
    - gosec
    - gosmopolitan
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - zerologlint
  disable:
    - contextcheck
    - err113
    - godox
    - testifylint
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 100
      statements: -1
      ignore-comments: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - godot
          - gosec
          - perfsprint
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
