# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appencryption.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61ppencryption.proto\x12\x13\x61sherah.apps.server\"\xb5\x01\n\x0eSessionRequest\x12/\n\x07\x65ncrypt\x18\x01 \x01(\x0b\x32\x1c.asherah.apps.server.EncryptH\x00\x12/\n\x07\x64\x65\x63rypt\x18\x02 \x01(\x0b\x32\x1c.asherah.apps.server.DecryptH\x00\x12\x36\n\x0bget_session\x18\x03 \x01(\x0b\x32\x1f.asherah.apps.server.GetSessionH\x00\x42\t\n\x07request\"\x17\n\x07\x45ncrypt\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"F\n\x07\x44\x65\x63rypt\x12;\n\x0f\x64\x61ta_row_record\x18\x01 \x01(\x0b\x32\".asherah.apps.server.DataRowRecord\"R\n\rDataRowRecord\x12\x33\n\x03key\x18\x01 \x01(\x0b\x32&.asherah.apps.server.EnvelopeKeyRecord\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"h\n\x11\x45nvelopeKeyRecord\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\x35\n\x0fparent_key_meta\x18\x03 \x01(\x0b\x32\x1c.asherah.apps.server.KeyMeta\"*\n\x07KeyMeta\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x03\x12\x0e\n\x06key_id\x18\x02 \x01(\t\"\"\n\nGetSession\x12\x14\n\x0cpartition_id\x18\x01 \x01(\t\" \n\rErrorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"N\n\x0f\x45ncryptResponse\x12;\n\x0f\x64\x61ta_row_record\x18\x01 \x01(\x0b\x32\".asherah.apps.server.DataRowRecord\"\x1f\n\x0f\x44\x65\x63ryptResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xdf\x01\n\x0fSessionResponse\x12@\n\x10\x65ncrypt_response\x18\x01 \x01(\x0b\x32$.asherah.apps.server.EncryptResponseH\x00\x12@\n\x10\x64\x65\x63rypt_response\x18\x02 \x01(\x0b\x32$.asherah.apps.server.DecryptResponseH\x00\x12<\n\x0e\x65rror_response\x18\x03 \x01(\x0b\x32\".asherah.apps.server.ErrorResponseH\x00\x42\n\n\x08response2i\n\rAppEncryption\x12X\n\x07Session\x12#.asherah.apps.server.SessionRequest\x1a$.asherah.apps.server.SessionResponse(\x01\x30\x01\x42\x38\n\x18\x63om.godaddy.asherah.grpcB\x13\x41ppEncryptionProtosZ\x07\x61pi;apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appencryption_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.godaddy.asherah.grpcB\023AppEncryptionProtosZ\007api;api'
  _SESSIONREQUEST._serialized_start=45
  _SESSIONREQUEST._serialized_end=226
  _ENCRYPT._serialized_start=228
  _ENCRYPT._serialized_end=251
  _DECRYPT._serialized_start=253
  _DECRYPT._serialized_end=323
  _DATAROWRECORD._serialized_start=325
  _DATAROWRECORD._serialized_end=407
  _ENVELOPEKEYRECORD._serialized_start=409
  _ENVELOPEKEYRECORD._serialized_end=513
  _KEYMETA._serialized_start=515
  _KEYMETA._serialized_end=557
  _GETSESSION._serialized_start=559
  _GETSESSION._serialized_end=593
  _ERRORRESPONSE._serialized_start=595
  _ERRORRESPONSE._serialized_end=627
  _ENCRYPTRESPONSE._serialized_start=629
  _ENCRYPTRESPONSE._serialized_end=707
  _DECRYPTRESPONSE._serialized_start=709
  _DECRYPTRESPONSE._serialized_end=740
  _SESSIONRESPONSE._serialized_start=743
  _SESSIONRESPONSE._serialized_end=966
  _APPENCRYPTION._serialized_start=968
  _APPENCRYPTION._serialized_end=1073
# @@protoc_insertion_point(module_scope)
