# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import appencryption_pb2 as appencryption__pb2


class AppEncryptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/asherah.apps.server.AppEncryption/Session',
                request_serializer=appencryption__pb2.SessionRequest.SerializeToString,
                response_deserializer=appencryption__pb2.SessionResponse.FromString,
                )


class AppEncryptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Session(self, request_iterator, context):
        """Performs session operations for a single partition.

        Each session must begin with a GetSession message with all subsequent
        Encrypt and Decrypt operations scoped its partition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppEncryptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=appencryption__pb2.SessionRequest.FromString,
                    response_serializer=appencryption__pb2.SessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asherah.apps.server.AppEncryption', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppEncryption(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/asherah.apps.server.AppEncryption/Session',
            appencryption__pb2.SessionRequest.SerializeToString,
            appencryption__pb2.SessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
