// This file is used by Code Analysis to suppress warnings
// that are generated by the build process.
// See https://learn.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files#global-suppressions

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1848:Use LoggerMessage delegates", Justification = "Debug logging messages don't require the performance improvement from LoggerMessage delegates")]
