version: '3'
services:
  myapp:
    image: "${ASHERAH_SAMPLE_CLIENT_IMAGE}"
    command: ["--socket", "/tmp/appencryption.sock", "--continuous", "--num-clients", "2"]
    volumes:
      - tmp:/tmp
    logging:
      driver: awslogs
      options:
        awslogs-group: asherah-samples
        awslogs-region: us-west-2
        awslogs-stream-prefix: myapp
  sidecar:
    image: "${ASHERAH_SAMPLE_SERVER_IMAGE}"
    environment:
      ASHERAH_SERVICE_NAME: myapp
      ASHERAH_PRODUCT_NAME: asherah-examples
      ASHERAH_EXPIRE_AFTER: 60m
      ASHERAH_CHECK_INTERVAL: 10m
      ASHERAH_KMS_MODE: static
      ASHERAH_METASTORE_MODE: memory
    command: ["--socket-file", "/tmp/appencryption.sock"]
    volumes:
      - tmp:/tmp
    logging:
      driver: awslogs
      options:
        awslogs-group: asherah-samples
        awslogs-region: us-west-2
        awslogs-stream-prefix: sidecar

volumes:
  tmp:
