// <auto-generated/>
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA2201:Do not raise reserved exception types", Justification = "Tests may intentionally throw general exceptions for coverage or negative testing.")]
