<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appencryption.proto

namespace Asherah\Apps\Server;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DataRowRecord represents an envelope containing data encypted by a DRK, the
 * encrypted DRK itself, and meta data of the key used to encrypt the DRK.
 *
 * Generated from protobuf message <code>asherah.apps.server.DataRowRecord</code>
 */
class DataRowRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.asherah.apps.server.EnvelopeKeyRecord key = 1;</code>
     */
    private $key = null;
    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    private $data = '';

    public function __construct() {
        \GPBMetadata\Appencryption::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.EnvelopeKeyRecord key = 1;</code>
     * @return \Asherah\Apps\Server\EnvelopeKeyRecord
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.EnvelopeKeyRecord key = 1;</code>
     * @param \Asherah\Apps\Server\EnvelopeKeyRecord $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\EnvelopeKeyRecord::class);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

