<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appencryption.proto

namespace Asherah\Apps\Server;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>asherah.apps.server.EncryptResponse</code>
 */
class EncryptResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.asherah.apps.server.DataRowRecord data_row_record = 1;</code>
     */
    private $data_row_record = null;

    public function __construct() {
        \GPBMetadata\Appencryption::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.DataRowRecord data_row_record = 1;</code>
     * @return \Asherah\Apps\Server\DataRowRecord
     */
    public function getDataRowRecord()
    {
        return $this->data_row_record;
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.DataRowRecord data_row_record = 1;</code>
     * @param \Asherah\Apps\Server\DataRowRecord $var
     * @return $this
     */
    public function setDataRowRecord($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\DataRowRecord::class);
        $this->data_row_record = $var;

        return $this;
    }

}

