<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appencryption.proto

namespace Asherah\Apps\Server;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>asherah.apps.server.EnvelopeKeyRecord</code>
 */
class EnvelopeKeyRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 created = 1;</code>
     */
    private $created = 0;
    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>.asherah.apps.server.KeyMeta parent_key_meta = 3;</code>
     */
    private $parent_key_meta = null;

    public function __construct() {
        \GPBMetadata\Appencryption::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 created = 1;</code>
     * @return int|string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Generated from protobuf field <code>int64 created = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.KeyMeta parent_key_meta = 3;</code>
     * @return \Asherah\Apps\Server\KeyMeta
     */
    public function getParentKeyMeta()
    {
        return $this->parent_key_meta;
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.KeyMeta parent_key_meta = 3;</code>
     * @param \Asherah\Apps\Server\KeyMeta $var
     * @return $this
     */
    public function setParentKeyMeta($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\KeyMeta::class);
        $this->parent_key_meta = $var;

        return $this;
    }

}

