<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appencryption.proto

namespace Asherah\Apps\Server;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>asherah.apps.server.SessionResponse</code>
 */
class SessionResponse extends \Google\Protobuf\Internal\Message
{
    protected $response;

    public function __construct() {
        \GPBMetadata\Appencryption::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.EncryptResponse encrypt_response = 1;</code>
     * @return \Asherah\Apps\Server\EncryptResponse
     */
    public function getEncryptResponse()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.EncryptResponse encrypt_response = 1;</code>
     * @param \Asherah\Apps\Server\EncryptResponse $var
     * @return $this
     */
    public function setEncryptResponse($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\EncryptResponse::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.DecryptResponse decrypt_response = 2;</code>
     * @return \Asherah\Apps\Server\DecryptResponse
     */
    public function getDecryptResponse()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.DecryptResponse decrypt_response = 2;</code>
     * @param \Asherah\Apps\Server\DecryptResponse $var
     * @return $this
     */
    public function setDecryptResponse($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\DecryptResponse::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.ErrorResponse error_response = 3;</code>
     * @return \Asherah\Apps\Server\ErrorResponse
     */
    public function getErrorResponse()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.ErrorResponse error_response = 3;</code>
     * @param \Asherah\Apps\Server\ErrorResponse $var
     * @return $this
     */
    public function setErrorResponse($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\ErrorResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

