<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appencryption.proto

namespace Asherah\Apps\Server;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SessionRequest represents an operation on an individual session
 *
 * Generated from protobuf message <code>asherah.apps.server.SessionRequest</code>
 */
class SessionRequest extends \Google\Protobuf\Internal\Message
{
    protected $request;

    public function __construct() {
        \GPBMetadata\Appencryption::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.Encrypt encrypt = 1;</code>
     * @return \Asherah\Apps\Server\Encrypt
     */
    public function getEncrypt()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.Encrypt encrypt = 1;</code>
     * @param \Asherah\Apps\Server\Encrypt $var
     * @return $this
     */
    public function setEncrypt($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\Encrypt::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.Decrypt decrypt = 2;</code>
     * @return \Asherah\Apps\Server\Decrypt
     */
    public function getDecrypt()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.Decrypt decrypt = 2;</code>
     * @param \Asherah\Apps\Server\Decrypt $var
     * @return $this
     */
    public function setDecrypt($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\Decrypt::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.GetSession get_session = 3;</code>
     * @return \Asherah\Apps\Server\GetSession
     */
    public function getGetSession()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.asherah.apps.server.GetSession get_session = 3;</code>
     * @param \Asherah\Apps\Server\GetSession $var
     * @return $this
     */
    public function setGetSession($var)
    {
        GPBUtil::checkMessage($var, \Asherah\Apps\Server\GetSession::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

