# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appencryption.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='appencryption.proto',
  package='asherah.apps.server',
  syntax='proto3',
  serialized_options=b'Z\007api;api',
  serialized_pb=b'\n\x13\x61ppencryption.proto\x12\x13\x61sherah.apps.server\"\xb5\x01\n\x0eSessionRequest\x12/\n\x07\x65ncrypt\x18\x01 \x01(\x0b\x32\x1c.asherah.apps.server.EncryptH\x00\x12/\n\x07\x64\x65\x63rypt\x18\x02 \x01(\x0b\x32\x1c.asherah.apps.server.DecryptH\x00\x12\x36\n\x0bget_session\x18\x03 \x01(\x0b\x32\x1f.asherah.apps.server.GetSessionH\x00\x42\t\n\x07request\"\x17\n\x07\x45ncrypt\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"F\n\x07\x44\x65\x63rypt\x12;\n\x0f\x64\x61ta_row_record\x18\x01 \x01(\x0b\x32\".asherah.apps.server.DataRowRecord\"R\n\rDataRowRecord\x12\x33\n\x03key\x18\x01 \x01(\x0b\x32&.asherah.apps.server.EnvelopeKeyRecord\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"h\n\x11\x45nvelopeKeyRecord\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\x35\n\x0fparent_key_meta\x18\x03 \x01(\x0b\x32\x1c.asherah.apps.server.KeyMeta\"*\n\x07KeyMeta\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x03\x12\x0e\n\x06key_id\x18\x02 \x01(\t\"\"\n\nGetSession\x12\x14\n\x0cpartition_id\x18\x01 \x01(\t\" \n\rErrorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"N\n\x0f\x45ncryptResponse\x12;\n\x0f\x64\x61ta_row_record\x18\x01 \x01(\x0b\x32\".asherah.apps.server.DataRowRecord\"\x1f\n\x0f\x44\x65\x63ryptResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xdf\x01\n\x0fSessionResponse\x12@\n\x10\x65ncrypt_response\x18\x01 \x01(\x0b\x32$.asherah.apps.server.EncryptResponseH\x00\x12@\n\x10\x64\x65\x63rypt_response\x18\x02 \x01(\x0b\x32$.asherah.apps.server.DecryptResponseH\x00\x12<\n\x0e\x65rror_response\x18\x03 \x01(\x0b\x32\".asherah.apps.server.ErrorResponseH\x00\x42\n\n\x08response2i\n\rAppEncryption\x12X\n\x07Session\x12#.asherah.apps.server.SessionRequest\x1a$.asherah.apps.server.SessionResponse(\x01\x30\x01\x42\tZ\x07\x61pi;apib\x06proto3'
)




_SESSIONREQUEST = _descriptor.Descriptor(
  name='SessionRequest',
  full_name='asherah.apps.server.SessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypt', full_name='asherah.apps.server.SessionRequest.encrypt', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decrypt', full_name='asherah.apps.server.SessionRequest.decrypt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_session', full_name='asherah.apps.server.SessionRequest.get_session', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='asherah.apps.server.SessionRequest.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=45,
  serialized_end=226,
)


_ENCRYPT = _descriptor.Descriptor(
  name='Encrypt',
  full_name='asherah.apps.server.Encrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='asherah.apps.server.Encrypt.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=251,
)


_DECRYPT = _descriptor.Descriptor(
  name='Decrypt',
  full_name='asherah.apps.server.Decrypt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_row_record', full_name='asherah.apps.server.Decrypt.data_row_record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=323,
)


_DATAROWRECORD = _descriptor.Descriptor(
  name='DataRowRecord',
  full_name='asherah.apps.server.DataRowRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='asherah.apps.server.DataRowRecord.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='asherah.apps.server.DataRowRecord.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=407,
)


_ENVELOPEKEYRECORD = _descriptor.Descriptor(
  name='EnvelopeKeyRecord',
  full_name='asherah.apps.server.EnvelopeKeyRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='created', full_name='asherah.apps.server.EnvelopeKeyRecord.created', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='asherah.apps.server.EnvelopeKeyRecord.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_key_meta', full_name='asherah.apps.server.EnvelopeKeyRecord.parent_key_meta', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=513,
)


_KEYMETA = _descriptor.Descriptor(
  name='KeyMeta',
  full_name='asherah.apps.server.KeyMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='created', full_name='asherah.apps.server.KeyMeta.created', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_id', full_name='asherah.apps.server.KeyMeta.key_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=557,
)


_GETSESSION = _descriptor.Descriptor(
  name='GetSession',
  full_name='asherah.apps.server.GetSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partition_id', full_name='asherah.apps.server.GetSession.partition_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=593,
)


_ERRORRESPONSE = _descriptor.Descriptor(
  name='ErrorResponse',
  full_name='asherah.apps.server.ErrorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='asherah.apps.server.ErrorResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=627,
)


_ENCRYPTRESPONSE = _descriptor.Descriptor(
  name='EncryptResponse',
  full_name='asherah.apps.server.EncryptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_row_record', full_name='asherah.apps.server.EncryptResponse.data_row_record', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=707,
)


_DECRYPTRESPONSE = _descriptor.Descriptor(
  name='DecryptResponse',
  full_name='asherah.apps.server.DecryptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='asherah.apps.server.DecryptResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=709,
  serialized_end=740,
)


_SESSIONRESPONSE = _descriptor.Descriptor(
  name='SessionResponse',
  full_name='asherah.apps.server.SessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypt_response', full_name='asherah.apps.server.SessionResponse.encrypt_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decrypt_response', full_name='asherah.apps.server.SessionResponse.decrypt_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_response', full_name='asherah.apps.server.SessionResponse.error_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='asherah.apps.server.SessionResponse.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=743,
  serialized_end=966,
)

_SESSIONREQUEST.fields_by_name['encrypt'].message_type = _ENCRYPT
_SESSIONREQUEST.fields_by_name['decrypt'].message_type = _DECRYPT
_SESSIONREQUEST.fields_by_name['get_session'].message_type = _GETSESSION
_SESSIONREQUEST.oneofs_by_name['request'].fields.append(
  _SESSIONREQUEST.fields_by_name['encrypt'])
_SESSIONREQUEST.fields_by_name['encrypt'].containing_oneof = _SESSIONREQUEST.oneofs_by_name['request']
_SESSIONREQUEST.oneofs_by_name['request'].fields.append(
  _SESSIONREQUEST.fields_by_name['decrypt'])
_SESSIONREQUEST.fields_by_name['decrypt'].containing_oneof = _SESSIONREQUEST.oneofs_by_name['request']
_SESSIONREQUEST.oneofs_by_name['request'].fields.append(
  _SESSIONREQUEST.fields_by_name['get_session'])
_SESSIONREQUEST.fields_by_name['get_session'].containing_oneof = _SESSIONREQUEST.oneofs_by_name['request']
_DECRYPT.fields_by_name['data_row_record'].message_type = _DATAROWRECORD
_DATAROWRECORD.fields_by_name['key'].message_type = _ENVELOPEKEYRECORD
_ENVELOPEKEYRECORD.fields_by_name['parent_key_meta'].message_type = _KEYMETA
_ENCRYPTRESPONSE.fields_by_name['data_row_record'].message_type = _DATAROWRECORD
_SESSIONRESPONSE.fields_by_name['encrypt_response'].message_type = _ENCRYPTRESPONSE
_SESSIONRESPONSE.fields_by_name['decrypt_response'].message_type = _DECRYPTRESPONSE
_SESSIONRESPONSE.fields_by_name['error_response'].message_type = _ERRORRESPONSE
_SESSIONRESPONSE.oneofs_by_name['response'].fields.append(
  _SESSIONRESPONSE.fields_by_name['encrypt_response'])
_SESSIONRESPONSE.fields_by_name['encrypt_response'].containing_oneof = _SESSIONRESPONSE.oneofs_by_name['response']
_SESSIONRESPONSE.oneofs_by_name['response'].fields.append(
  _SESSIONRESPONSE.fields_by_name['decrypt_response'])
_SESSIONRESPONSE.fields_by_name['decrypt_response'].containing_oneof = _SESSIONRESPONSE.oneofs_by_name['response']
_SESSIONRESPONSE.oneofs_by_name['response'].fields.append(
  _SESSIONRESPONSE.fields_by_name['error_response'])
_SESSIONRESPONSE.fields_by_name['error_response'].containing_oneof = _SESSIONRESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['SessionRequest'] = _SESSIONREQUEST
DESCRIPTOR.message_types_by_name['Encrypt'] = _ENCRYPT
DESCRIPTOR.message_types_by_name['Decrypt'] = _DECRYPT
DESCRIPTOR.message_types_by_name['DataRowRecord'] = _DATAROWRECORD
DESCRIPTOR.message_types_by_name['EnvelopeKeyRecord'] = _ENVELOPEKEYRECORD
DESCRIPTOR.message_types_by_name['KeyMeta'] = _KEYMETA
DESCRIPTOR.message_types_by_name['GetSession'] = _GETSESSION
DESCRIPTOR.message_types_by_name['ErrorResponse'] = _ERRORRESPONSE
DESCRIPTOR.message_types_by_name['EncryptResponse'] = _ENCRYPTRESPONSE
DESCRIPTOR.message_types_by_name['DecryptResponse'] = _DECRYPTRESPONSE
DESCRIPTOR.message_types_by_name['SessionResponse'] = _SESSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionRequest = _reflection.GeneratedProtocolMessageType('SessionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONREQUEST,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.SessionRequest)
  })
_sym_db.RegisterMessage(SessionRequest)

Encrypt = _reflection.GeneratedProtocolMessageType('Encrypt', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPT,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.Encrypt)
  })
_sym_db.RegisterMessage(Encrypt)

Decrypt = _reflection.GeneratedProtocolMessageType('Decrypt', (_message.Message,), {
  'DESCRIPTOR' : _DECRYPT,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.Decrypt)
  })
_sym_db.RegisterMessage(Decrypt)

DataRowRecord = _reflection.GeneratedProtocolMessageType('DataRowRecord', (_message.Message,), {
  'DESCRIPTOR' : _DATAROWRECORD,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.DataRowRecord)
  })
_sym_db.RegisterMessage(DataRowRecord)

EnvelopeKeyRecord = _reflection.GeneratedProtocolMessageType('EnvelopeKeyRecord', (_message.Message,), {
  'DESCRIPTOR' : _ENVELOPEKEYRECORD,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.EnvelopeKeyRecord)
  })
_sym_db.RegisterMessage(EnvelopeKeyRecord)

KeyMeta = _reflection.GeneratedProtocolMessageType('KeyMeta', (_message.Message,), {
  'DESCRIPTOR' : _KEYMETA,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.KeyMeta)
  })
_sym_db.RegisterMessage(KeyMeta)

GetSession = _reflection.GeneratedProtocolMessageType('GetSession', (_message.Message,), {
  'DESCRIPTOR' : _GETSESSION,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.GetSession)
  })
_sym_db.RegisterMessage(GetSession)

ErrorResponse = _reflection.GeneratedProtocolMessageType('ErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _ERRORRESPONSE,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.ErrorResponse)
  })
_sym_db.RegisterMessage(ErrorResponse)

EncryptResponse = _reflection.GeneratedProtocolMessageType('EncryptResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTRESPONSE,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.EncryptResponse)
  })
_sym_db.RegisterMessage(EncryptResponse)

DecryptResponse = _reflection.GeneratedProtocolMessageType('DecryptResponse', (_message.Message,), {
  'DESCRIPTOR' : _DECRYPTRESPONSE,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.DecryptResponse)
  })
_sym_db.RegisterMessage(DecryptResponse)

SessionResponse = _reflection.GeneratedProtocolMessageType('SessionResponse', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONRESPONSE,
  '__module__' : 'appencryption_pb2'
  # @@protoc_insertion_point(class_scope:asherah.apps.server.SessionResponse)
  })
_sym_db.RegisterMessage(SessionResponse)


DESCRIPTOR._options = None

_APPENCRYPTION = _descriptor.ServiceDescriptor(
  name='AppEncryption',
  full_name='asherah.apps.server.AppEncryption',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=968,
  serialized_end=1073,
  methods=[
  _descriptor.MethodDescriptor(
    name='Session',
    full_name='asherah.apps.server.AppEncryption.Session',
    index=0,
    containing_service=None,
    input_type=_SESSIONREQUEST,
    output_type=_SESSIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_APPENCRYPTION)

DESCRIPTOR.services_by_name['AppEncryption'] = _APPENCRYPTION

# @@protoc_insertion_point(module_scope)
