name: '[C#] SecureMemory Release'

on:
  workflow_call:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  release:
    if: github.repository == 'godaddy/asherah'
    name: Release C# SecureMemory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Fetch all tags
        run: git fetch --prune --unshallow --tags

      - name: Cache dotnet packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-securememory-${{ hashFiles('csharp/SecureMemory/**/*.csproj') }}-v2

      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: csharp-secure-memory
          path: |
            ${{ github.workspace }}/csharp/SecureMemory/SecureMemory
            ${{ github.workspace }}/csharp/SecureMemory/PlatformNative

      - name: Initialize Environment Variables
        run: |
          echo "BASE_VERSION=$(grep -o '<Version>.*<.*>' Directory.Build.props | sed 's/<Version>\(.*\)<.*>/\1/')" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$(echo ${BASE_VERSION} | cut -f2 -d'-')" >> $GITHUB_ENV
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        working-directory: csharp/SecureMemory

      - name: Publish C# SecureMemory
        if: startsWith(env.BRANCH, 'release-') && env.VERSION_SUFFIX != 'alpha'
        run: |
          ./scripts/release_prod.sh
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
        working-directory: csharp/SecureMemory
