name: '[C#] Logging CI'

on:
  workflow_dispatch:

  push:
    paths:
      - 'csharp/Logging/**'
      - '.github/workflows/csharp-logging-*'

  pull_request:
    branches:
      - main
    paths:
      - 'csharp/Logging/**'
      - '.github/workflows/csharp-logging-*'

permissions:
  contents: read

jobs:
  logging-main:
    name: 'Build & Test'
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.upload-artifact.outputs.artifact_id }}
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Add workspace to safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Cache dotnet packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-logging-${{ hashFiles('csharp/Logging/**/*.csproj') }}-v2

      - name: Build
        run: |
          cd csharp/Logging
          ./scripts/clean.sh
          ./scripts/build.sh

      - name: Run unit tests
        run: |
          cd csharp/Logging
          ./scripts/test.sh

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: csharp-logging
          path: |
            csharp/Logging/Logging/bin/**
            csharp/Logging/Logging/obj/**

  release:
    if: startsWith(github.ref, 'refs/heads/release-')
    needs: logging-main
    permissions:
      contents: write
    name: Release
    uses: ./.github/workflows/csharp-logging-release.yml
    secrets: inherit
