name: '[C#] SecureMemory CI'

on:
  workflow_dispatch:

  push:
    paths:
      - 'csharp/SecureMemory/**'
      - '.github/workflows/csharp-securememory-*'

  pull_request:
    branches:
      - main
    paths:
      - 'csharp/SecureMemory/**'
      - '.github/workflows/csharp-securememory-*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-csharp-sm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.upload-artifact.outputs.artifact_id }}
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Add workspace to safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Cache dotnet packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-securememory-${{ hashFiles('csharp/SecureMemory/**/*.csproj') }}-v2

      - name: Build
        run: |
          cd csharp/SecureMemory
          ./scripts/clean.sh
          ./scripts/build.sh

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: csharp-secure-memory
          path: |
            csharp/SecureMemory/SecureMemory/bin/**
            csharp/SecureMemory/SecureMemory/obj/**
            csharp/SecureMemory/PlatformNative/bin/**
            csharp/SecureMemory/PlatformNative/obj/**
            csharp/SecureMemory/SecureMemory.Tests/bin/**
            csharp/SecureMemory/SecureMemory.Tests/obj/**

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache dotnet packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-securememory-${{ hashFiles('csharp/SecureMemory/**/*.csproj') }}-v2

      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: csharp-secure-memory
          path: ${{ github.workspace }}/csharp/SecureMemory

      - name: Install libssl-1.1
        run: |
          wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Run unit tests
        run: |
          cd csharp/SecureMemory
          ./scripts/test.sh

      - name: Unit test summary
        uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2.3.0
        with:
          paths: 'csharp/SecureMemory/SecureMemory.Tests/test-result.xml'
        if: always()

  release:
    if: startsWith(github.ref, 'refs/heads/release-')
    needs: test
    permissions:
      contents: write
    name: Release
    uses: ./.github/workflows/csharp-securememory-release.yml
    secrets: inherit
