name: '[Go] SecureMemory Bench'

on:
  workflow_dispatch:
    inputs:
      go-version:
        description: 'Go version'
        type: string
        default: 'stable'

  workflow_call:
    inputs:
      go-version:
        description: 'Go version'
        type: string
        default: 'stable'

permissions:
  contents: read

jobs:
  bench:
    name: 'Run Benchmarks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ inputs.go-version }}
          cache-dependency-path: 'go/*/go.sum'

      - name: Install dependencies
        run: |
          cd go/securememory
          go get .

      - name: Run benchmarks
        run: |
          cd go/securememory
          sudo prlimit --pid $$ --core=-1
          sudo prlimit --pid $$ --memlock=-1:-1
          ./scripts/benchmark_test.sh
