name: '[Go] SecureMemory Release'

on:
  workflow_call:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  release:
    if: github.repository == 'godaddy/asherah'
    name: Release Go SecureMemory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Fetch all tags
        run: git fetch --prune --unshallow --tags

      - name: Initialize Environment Variables
        run: |
          echo "BASE_VERSION=$(cat .versionfile)" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$(echo ${BASE_VERSION} | cut -f2 -d'-')" >> $GITHUB_ENV
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        working-directory: go/securememory

      - name: Publish Go SecureMemory
        if: startsWith(env.BRANCH, 'release-') && env.VERSION_SUFFIX != 'alpha'
        run: |
          ./scripts/release_prod.sh
        working-directory: go/securememory
