name: '[Java] AppEncryption Integration Test'

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        type: string
        default: '17'

permissions:
  contents: read

env:
  DYNAMODB_HOSTNAME: dynamodb
  MYSQL_HOSTNAME: mysql
  MYSQL_DATABASE: testdb
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: Password123
  DISABLE_TESTCONTAINERS: true
  AWS_ACCESS_KEY_ID: dummykey
  AWS_SECRET_ACCESS_KEY: dummy_secret
  AWS_DEFAULT_REGION: us-west-2
  AWS_REGION: us-west-2

jobs:
  integration-test:
    name: 'Run Integration Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'java/*/pom.xml'

      - name: Run integration tests
        run: |
          cd java/app-encryption
          sudo prlimit --pid $$ --core=-1
          sudo prlimit --pid $$ --memlock=-1:-1
          ./scripts/integration_test.sh

      - name: Integration test summary
        uses: test-summary/action@37b508cfee6d4d080eedd00b5bb240a6a784a6a5 # v2.3.0
        with:
          paths: 'java/app-encryption/target/failsafe-reports/TEST-*.xml'
        if: always()
