// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/appencryption.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SessionRequest represents an operation on an individual session
type SessionRequest struct {
	// Types that are valid to be assigned to Request:
	//	*SessionRequest_Encrypt
	//	*SessionRequest_Decrypt
	//	*SessionRequest_GetSession
	Request              isSessionRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{0}
}

func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(m, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

type isSessionRequest_Request interface {
	isSessionRequest_Request()
}

type SessionRequest_Encrypt struct {
	Encrypt *Encrypt `protobuf:"bytes,1,opt,name=encrypt,proto3,oneof"`
}

type SessionRequest_Decrypt struct {
	Decrypt *Decrypt `protobuf:"bytes,2,opt,name=decrypt,proto3,oneof"`
}

type SessionRequest_GetSession struct {
	GetSession *GetSession `protobuf:"bytes,3,opt,name=get_session,json=getSession,proto3,oneof"`
}

func (*SessionRequest_Encrypt) isSessionRequest_Request() {}

func (*SessionRequest_Decrypt) isSessionRequest_Request() {}

func (*SessionRequest_GetSession) isSessionRequest_Request() {}

func (m *SessionRequest) GetRequest() isSessionRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SessionRequest) GetEncrypt() *Encrypt {
	if x, ok := m.GetRequest().(*SessionRequest_Encrypt); ok {
		return x.Encrypt
	}
	return nil
}

func (m *SessionRequest) GetDecrypt() *Decrypt {
	if x, ok := m.GetRequest().(*SessionRequest_Decrypt); ok {
		return x.Decrypt
	}
	return nil
}

func (m *SessionRequest) GetGetSession() *GetSession {
	if x, ok := m.GetRequest().(*SessionRequest_GetSession); ok {
		return x.GetSession
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SessionRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SessionRequest_Encrypt)(nil),
		(*SessionRequest_Decrypt)(nil),
		(*SessionRequest_GetSession)(nil),
	}
}

type Encrypt struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Encrypt) Reset()         { *m = Encrypt{} }
func (m *Encrypt) String() string { return proto.CompactTextString(m) }
func (*Encrypt) ProtoMessage()    {}
func (*Encrypt) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{1}
}

func (m *Encrypt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Encrypt.Unmarshal(m, b)
}
func (m *Encrypt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Encrypt.Marshal(b, m, deterministic)
}
func (m *Encrypt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Encrypt.Merge(m, src)
}
func (m *Encrypt) XXX_Size() int {
	return xxx_messageInfo_Encrypt.Size(m)
}
func (m *Encrypt) XXX_DiscardUnknown() {
	xxx_messageInfo_Encrypt.DiscardUnknown(m)
}

var xxx_messageInfo_Encrypt proto.InternalMessageInfo

func (m *Encrypt) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Decrypt struct {
	DataRowRecord        *DataRowRecord `protobuf:"bytes,1,opt,name=data_row_record,json=dataRowRecord,proto3" json:"data_row_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Decrypt) Reset()         { *m = Decrypt{} }
func (m *Decrypt) String() string { return proto.CompactTextString(m) }
func (*Decrypt) ProtoMessage()    {}
func (*Decrypt) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{2}
}

func (m *Decrypt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Decrypt.Unmarshal(m, b)
}
func (m *Decrypt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Decrypt.Marshal(b, m, deterministic)
}
func (m *Decrypt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Decrypt.Merge(m, src)
}
func (m *Decrypt) XXX_Size() int {
	return xxx_messageInfo_Decrypt.Size(m)
}
func (m *Decrypt) XXX_DiscardUnknown() {
	xxx_messageInfo_Decrypt.DiscardUnknown(m)
}

var xxx_messageInfo_Decrypt proto.InternalMessageInfo

func (m *Decrypt) GetDataRowRecord() *DataRowRecord {
	if m != nil {
		return m.DataRowRecord
	}
	return nil
}

// DataRowRecord represents an envelope containing data encypted by a DRK, the
// encrypted DRK itself, and meta data of the key used to encrypt the DRK.
type DataRowRecord struct {
	Key                  *EnvelopeKeyRecord `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DataRowRecord) Reset()         { *m = DataRowRecord{} }
func (m *DataRowRecord) String() string { return proto.CompactTextString(m) }
func (*DataRowRecord) ProtoMessage()    {}
func (*DataRowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{3}
}

func (m *DataRowRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRowRecord.Unmarshal(m, b)
}
func (m *DataRowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRowRecord.Marshal(b, m, deterministic)
}
func (m *DataRowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRowRecord.Merge(m, src)
}
func (m *DataRowRecord) XXX_Size() int {
	return xxx_messageInfo_DataRowRecord.Size(m)
}
func (m *DataRowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DataRowRecord proto.InternalMessageInfo

func (m *DataRowRecord) GetKey() *EnvelopeKeyRecord {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DataRowRecord) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EnvelopeKeyRecord struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ParentKeyMeta        *KeyMeta `protobuf:"bytes,3,opt,name=parent_key_meta,json=parentKeyMeta,proto3" json:"parent_key_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvelopeKeyRecord) Reset()         { *m = EnvelopeKeyRecord{} }
func (m *EnvelopeKeyRecord) String() string { return proto.CompactTextString(m) }
func (*EnvelopeKeyRecord) ProtoMessage()    {}
func (*EnvelopeKeyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{4}
}

func (m *EnvelopeKeyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvelopeKeyRecord.Unmarshal(m, b)
}
func (m *EnvelopeKeyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvelopeKeyRecord.Marshal(b, m, deterministic)
}
func (m *EnvelopeKeyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvelopeKeyRecord.Merge(m, src)
}
func (m *EnvelopeKeyRecord) XXX_Size() int {
	return xxx_messageInfo_EnvelopeKeyRecord.Size(m)
}
func (m *EnvelopeKeyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvelopeKeyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_EnvelopeKeyRecord proto.InternalMessageInfo

func (m *EnvelopeKeyRecord) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *EnvelopeKeyRecord) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *EnvelopeKeyRecord) GetParentKeyMeta() *KeyMeta {
	if m != nil {
		return m.ParentKeyMeta
	}
	return nil
}

type KeyMeta struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	KeyId                string   `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyMeta) Reset()         { *m = KeyMeta{} }
func (m *KeyMeta) String() string { return proto.CompactTextString(m) }
func (*KeyMeta) ProtoMessage()    {}
func (*KeyMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{5}
}

func (m *KeyMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyMeta.Unmarshal(m, b)
}
func (m *KeyMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyMeta.Marshal(b, m, deterministic)
}
func (m *KeyMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyMeta.Merge(m, src)
}
func (m *KeyMeta) XXX_Size() int {
	return xxx_messageInfo_KeyMeta.Size(m)
}
func (m *KeyMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyMeta.DiscardUnknown(m)
}

var xxx_messageInfo_KeyMeta proto.InternalMessageInfo

func (m *KeyMeta) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *KeyMeta) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

type GetSession struct {
	PartitionId          string   `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSession) Reset()         { *m = GetSession{} }
func (m *GetSession) String() string { return proto.CompactTextString(m) }
func (*GetSession) ProtoMessage()    {}
func (*GetSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{6}
}

func (m *GetSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSession.Unmarshal(m, b)
}
func (m *GetSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSession.Marshal(b, m, deterministic)
}
func (m *GetSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSession.Merge(m, src)
}
func (m *GetSession) XXX_Size() int {
	return xxx_messageInfo_GetSession.Size(m)
}
func (m *GetSession) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSession.DiscardUnknown(m)
}

var xxx_messageInfo_GetSession proto.InternalMessageInfo

func (m *GetSession) GetPartitionId() string {
	if m != nil {
		return m.PartitionId
	}
	return ""
}

type ErrorResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{7}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EncryptResponse struct {
	DataRowRecord        *DataRowRecord `protobuf:"bytes,1,opt,name=data_row_record,json=dataRowRecord,proto3" json:"data_row_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EncryptResponse) Reset()         { *m = EncryptResponse{} }
func (m *EncryptResponse) String() string { return proto.CompactTextString(m) }
func (*EncryptResponse) ProtoMessage()    {}
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{8}
}

func (m *EncryptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptResponse.Unmarshal(m, b)
}
func (m *EncryptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptResponse.Marshal(b, m, deterministic)
}
func (m *EncryptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptResponse.Merge(m, src)
}
func (m *EncryptResponse) XXX_Size() int {
	return xxx_messageInfo_EncryptResponse.Size(m)
}
func (m *EncryptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptResponse proto.InternalMessageInfo

func (m *EncryptResponse) GetDataRowRecord() *DataRowRecord {
	if m != nil {
		return m.DataRowRecord
	}
	return nil
}

type DecryptResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptResponse) Reset()         { *m = DecryptResponse{} }
func (m *DecryptResponse) String() string { return proto.CompactTextString(m) }
func (*DecryptResponse) ProtoMessage()    {}
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{9}
}

func (m *DecryptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptResponse.Unmarshal(m, b)
}
func (m *DecryptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptResponse.Marshal(b, m, deterministic)
}
func (m *DecryptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptResponse.Merge(m, src)
}
func (m *DecryptResponse) XXX_Size() int {
	return xxx_messageInfo_DecryptResponse.Size(m)
}
func (m *DecryptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptResponse proto.InternalMessageInfo

func (m *DecryptResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SessionResponse struct {
	// Types that are valid to be assigned to Response:
	//	*SessionResponse_EncryptResponse
	//	*SessionResponse_DecryptResponse
	//	*SessionResponse_ErrorResponse
	Response             isSessionResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SessionResponse) Reset()         { *m = SessionResponse{} }
func (m *SessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()    {}
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6761fa4a2ef3a2e9, []int{10}
}

func (m *SessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponse.Unmarshal(m, b)
}
func (m *SessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponse.Marshal(b, m, deterministic)
}
func (m *SessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponse.Merge(m, src)
}
func (m *SessionResponse) XXX_Size() int {
	return xxx_messageInfo_SessionResponse.Size(m)
}
func (m *SessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponse proto.InternalMessageInfo

type isSessionResponse_Response interface {
	isSessionResponse_Response()
}

type SessionResponse_EncryptResponse struct {
	EncryptResponse *EncryptResponse `protobuf:"bytes,1,opt,name=encrypt_response,json=encryptResponse,proto3,oneof"`
}

type SessionResponse_DecryptResponse struct {
	DecryptResponse *DecryptResponse `protobuf:"bytes,2,opt,name=decrypt_response,json=decryptResponse,proto3,oneof"`
}

type SessionResponse_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,3,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

func (*SessionResponse_EncryptResponse) isSessionResponse_Response() {}

func (*SessionResponse_DecryptResponse) isSessionResponse_Response() {}

func (*SessionResponse_ErrorResponse) isSessionResponse_Response() {}

func (m *SessionResponse) GetResponse() isSessionResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SessionResponse) GetEncryptResponse() *EncryptResponse {
	if x, ok := m.GetResponse().(*SessionResponse_EncryptResponse); ok {
		return x.EncryptResponse
	}
	return nil
}

func (m *SessionResponse) GetDecryptResponse() *DecryptResponse {
	if x, ok := m.GetResponse().(*SessionResponse_DecryptResponse); ok {
		return x.DecryptResponse
	}
	return nil
}

func (m *SessionResponse) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetResponse().(*SessionResponse_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SessionResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SessionResponse_EncryptResponse)(nil),
		(*SessionResponse_DecryptResponse)(nil),
		(*SessionResponse_ErrorResponse)(nil),
	}
}

func init() {
	proto.RegisterType((*SessionRequest)(nil), "asherah.apps.server.SessionRequest")
	proto.RegisterType((*Encrypt)(nil), "asherah.apps.server.Encrypt")
	proto.RegisterType((*Decrypt)(nil), "asherah.apps.server.Decrypt")
	proto.RegisterType((*DataRowRecord)(nil), "asherah.apps.server.DataRowRecord")
	proto.RegisterType((*EnvelopeKeyRecord)(nil), "asherah.apps.server.EnvelopeKeyRecord")
	proto.RegisterType((*KeyMeta)(nil), "asherah.apps.server.KeyMeta")
	proto.RegisterType((*GetSession)(nil), "asherah.apps.server.GetSession")
	proto.RegisterType((*ErrorResponse)(nil), "asherah.apps.server.ErrorResponse")
	proto.RegisterType((*EncryptResponse)(nil), "asherah.apps.server.EncryptResponse")
	proto.RegisterType((*DecryptResponse)(nil), "asherah.apps.server.DecryptResponse")
	proto.RegisterType((*SessionResponse)(nil), "asherah.apps.server.SessionResponse")
}

func init() {
	proto.RegisterFile("protos/appencryption.proto", fileDescriptor_6761fa4a2ef3a2e9)
}

var fileDescriptor_6761fa4a2ef3a2e9 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x13, 0xa8, 0xc9, 0xa4, 0xae, 0xc3, 0x22, 0xa4, 0xa8, 0x02, 0x01, 0xa6, 0xa0, 0x72,
	0x71, 0x51, 0xb9, 0x54, 0x70, 0x22, 0x6a, 0x44, 0x4a, 0xc4, 0xa1, 0x8b, 0x90, 0x10, 0x52, 0x65,
	0x2d, 0xf1, 0x28, 0xb5, 0x42, 0xbd, 0xcb, 0xee, 0xd2, 0xca, 0x3f, 0x80, 0x3b, 0xff, 0x8d, 0x3f,
	0x84, 0x6c, 0x8f, 0x9d, 0x0f, 0x8c, 0x4f, 0xdc, 0x3c, 0xe3, 0xf7, 0xde, 0xbc, 0xd9, 0xd9, 0x59,
	0xd8, 0x57, 0x5a, 0x5a, 0x69, 0x8e, 0x84, 0x52, 0x98, 0xce, 0x75, 0xa6, 0x6c, 0x22, 0xd3, 0xb0,
	0x48, 0xb2, 0x7b, 0xc2, 0x5c, 0xa2, 0x16, 0x97, 0xa1, 0x50, 0xca, 0x84, 0x06, 0xf5, 0x35, 0xea,
	0xe0, 0xb7, 0x03, 0x7b, 0x1f, 0xd1, 0x98, 0x44, 0xa6, 0x1c, 0xbf, 0xff, 0x40, 0x63, 0xd9, 0x09,
	0xb8, 0xc4, 0x1d, 0x39, 0x8f, 0x9d, 0xc3, 0xc1, 0xf1, 0x83, 0xb0, 0x81, 0x19, 0x4e, 0x4a, 0xcc,
	0xb4, 0xc3, 0x2b, 0x78, 0xce, 0x8c, 0xb1, 0x64, 0x76, 0x5b, 0x98, 0xa7, 0x58, 0x33, 0x09, 0xce,
	0xc6, 0x30, 0x58, 0xa0, 0x8d, 0x4c, 0xe9, 0x64, 0xd4, 0x2b, 0xd8, 0x8f, 0x1a, 0xd9, 0xef, 0xd0,
	0x92, 0xe1, 0x69, 0x87, 0xc3, 0xa2, 0x8e, 0xc6, 0x7d, 0x70, 0x75, 0xd9, 0x42, 0xf0, 0x10, 0x5c,
	0xb2, 0xc7, 0x18, 0xdc, 0x8a, 0x85, 0x15, 0x45, 0x2b, 0xbb, 0xbc, 0xf8, 0x0e, 0x3e, 0x81, 0x4b,
	0x1e, 0xd8, 0x7b, 0xf0, 0xf3, 0x54, 0xa4, 0xe5, 0x4d, 0xa4, 0x71, 0x2e, 0x75, 0x4c, 0x4d, 0x07,
	0xcd, 0xd6, 0x85, 0x15, 0x5c, 0xde, 0xf0, 0x02, 0xc9, 0xbd, 0x78, 0x3d, 0x0c, 0x2e, 0xc0, 0xdb,
	0xf8, 0xcf, 0x4e, 0xa0, 0xb7, 0xc4, 0x8c, 0x04, 0x9f, 0xff, 0xe3, 0x14, 0xaf, 0xf1, 0x9b, 0x54,
	0x38, 0xc3, 0x8c, 0x44, 0x73, 0x4a, 0xed, 0xba, 0xbb, 0xe6, 0xfa, 0xa7, 0x03, 0x77, 0xff, 0x82,
	0xb3, 0x11, 0xb8, 0x73, 0x8d, 0xc2, 0x62, 0x69, 0xbc, 0xc7, 0xab, 0x90, 0x0d, 0xcb, 0xea, 0xa5,
	0x44, 0xa1, 0x7a, 0x0a, 0xbe, 0x12, 0x1a, 0x53, 0x1b, 0x2d, 0x31, 0x8b, 0xae, 0xd0, 0x0a, 0x3a,
	0xe9, 0xe6, 0x39, 0xcd, 0x30, 0xfb, 0x80, 0x56, 0x70, 0xaf, 0x24, 0x51, 0x18, 0xbc, 0x06, 0x97,
	0x3e, 0x5b, 0x8a, 0xdf, 0x87, 0x9d, 0xbc, 0x46, 0x12, 0x17, 0xf5, 0xfb, 0xfc, 0xf6, 0x12, 0xb3,
	0xb3, 0x38, 0x38, 0x02, 0x58, 0xcd, 0x8f, 0x3d, 0x81, 0x5d, 0x25, 0xb4, 0x4d, 0xf2, 0x4b, 0x9a,
	0x43, 0x9d, 0x02, 0x3a, 0xa8, 0x73, 0x67, 0x71, 0xf0, 0x02, 0xbc, 0x89, 0xd6, 0x52, 0x73, 0x34,
	0x4a, 0xa6, 0x06, 0xf3, 0x92, 0x57, 0x68, 0x8c, 0x58, 0x20, 0xc1, 0xab, 0x30, 0xb8, 0x00, 0x9f,
	0x86, 0x5e, 0x83, 0xff, 0xe7, 0x74, 0x9f, 0x81, 0x4f, 0x97, 0xa6, 0x96, 0x6f, 0xba, 0x5b, 0xbf,
	0xba, 0xe0, 0xd7, 0x0b, 0x45, 0xb8, 0x73, 0x18, 0xd2, 0x8a, 0x44, 0x9a, 0x72, 0xe4, 0xe3, 0xa0,
	0x6d, 0xb5, 0x2a, 0xfe, 0xb4, 0xc3, 0x7d, 0xdc, 0xea, 0xec, 0x1c, 0x86, 0xb4, 0x3b, 0x2b, 0xc9,
	0x6e, 0x8b, 0xe4, 0x96, 0xf5, 0x5c, 0x32, 0xde, 0xea, 0x66, 0x06, 0x7b, 0x98, 0x1f, 0xf5, 0x4a,
	0xb0, 0xd7, 0x72, 0x56, 0x1b, 0x53, 0x99, 0x76, 0xb8, 0x87, 0xeb, 0x89, 0x31, 0xc0, 0x9d, 0x4a,
	0xe6, 0x38, 0x01, 0xef, 0xad, 0x52, 0x93, 0xfa, 0x3d, 0x62, 0x9f, 0xc1, 0xad, 0xae, 0xc0, 0xd3,
	0x46, 0xf1, 0xcd, 0x17, 0x69, 0xff, 0xa0, 0x1d, 0x54, 0x96, 0x39, 0x74, 0x5e, 0x3a, 0xe3, 0xfe,
	0x17, 0x57, 0xa8, 0xe4, 0x8d, 0x50, 0xc9, 0xd7, 0x9d, 0xe2, 0xd5, 0x7b, 0xf5, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x37, 0x9c, 0xbd, 0x35, 0x13, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AppEncryptionClient is the client API for AppEncryption service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppEncryptionClient interface {
	// Performs session operations for a single partition.
	//
	// Each session must begin with a GetSession message with all subsequent
	// Encrypt and Decrypt operations scoped its partition.
	Session(ctx context.Context, opts ...grpc.CallOption) (AppEncryption_SessionClient, error)
}

type appEncryptionClient struct {
	cc grpc.ClientConnInterface
}

func NewAppEncryptionClient(cc grpc.ClientConnInterface) AppEncryptionClient {
	return &appEncryptionClient{cc}
}

func (c *appEncryptionClient) Session(ctx context.Context, opts ...grpc.CallOption) (AppEncryption_SessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AppEncryption_serviceDesc.Streams[0], "/asherah.apps.server.AppEncryption/Session", opts...)
	if err != nil {
		return nil, err
	}
	x := &appEncryptionSessionClient{stream}
	return x, nil
}

type AppEncryption_SessionClient interface {
	Send(*SessionRequest) error
	Recv() (*SessionResponse, error)
	grpc.ClientStream
}

type appEncryptionSessionClient struct {
	grpc.ClientStream
}

func (x *appEncryptionSessionClient) Send(m *SessionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *appEncryptionSessionClient) Recv() (*SessionResponse, error) {
	m := new(SessionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AppEncryptionServer is the server API for AppEncryption service.
type AppEncryptionServer interface {
	// Performs session operations for a single partition.
	//
	// Each session must begin with a GetSession message with all subsequent
	// Encrypt and Decrypt operations scoped its partition.
	Session(AppEncryption_SessionServer) error
}

// UnimplementedAppEncryptionServer can be embedded to have forward compatible implementations.
type UnimplementedAppEncryptionServer struct {
}

func (*UnimplementedAppEncryptionServer) Session(srv AppEncryption_SessionServer) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}

func RegisterAppEncryptionServer(s *grpc.Server, srv AppEncryptionServer) {
	s.RegisterService(&_AppEncryption_serviceDesc, srv)
}

func _AppEncryption_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AppEncryptionServer).Session(&appEncryptionSessionServer{stream})
}

type AppEncryption_SessionServer interface {
	Send(*SessionResponse) error
	Recv() (*SessionRequest, error)
	grpc.ServerStream
}

type appEncryptionSessionServer struct {
	grpc.ServerStream
}

func (x *appEncryptionSessionServer) Send(m *SessionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *appEncryptionSessionServer) Recv() (*SessionRequest, error) {
	m := new(SessionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AppEncryption_serviceDesc = grpc.ServiceDesc{
	ServiceName: "asherah.apps.server.AppEncryption",
	HandlerType: (*AppEncryptionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _AppEncryption_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/appencryption.proto",
}
